### ISSUE TITLE
TypeError: Syntax error in regular expression

### ISSUE THREAD

**Issue by nickoneill** [5calls/5calls#324]
https://sentry.io/5calls/5-calls/issues/295883891/

IE 11 regex formats are non-standard. Apparently using regex literals and not `new Regexp(...)` fixes this.

```
TypeError: Syntax error in regular expression
  at reducers.receiveTownHallData (/js/app.js:6:31607)
  at Anonymous function (/js/app.js:1:7581)
  at Anonymous function (/js/app.js:4:11767)
  at Anonymous function (/js/app.js:4:11492)
```

**Comment by nickoneill** [comment]
https://sentry.io/5calls/5-calls/issues/295684512/

**Comment by nickoneill** [comment]
Two issues in sentry come up that seem roughly related to the regex on `main.js` at 278. Pushing a PR to do some testing now...

**Comment by nickoneill** [comment]
Fixed
