### ISSUE TITLE
TypeError: null is not an object (evaluating 's.querySelector')

### ISSUE THREAD

**Issue by nickoneill** [5calls/5calls#335]
https://sentry.io/5calls/5-calls/issues/256353396/

```
TypeError: null is not an object (evaluating 's.querySelector')
  at o (/js/app.js:7:23616)
  at exports (/js/app.js:6:19105)
  at exports (/js/app.js:6:12754)
  at exports (/js/app.js:6:44826)
  at exports (/js/app.js:7:38386)
...
(5 additional frame(s) were not displayed)
```

**Comment by nickoneill** [comment]
There are a few of these in Sentry, all different versions centered around the `.querySelector` line in `translation.js` around L34. Other one is `errorCannot find function querySelector in object [object XMLDocument].` Mainly MobileSafari and a few additional old/obscure platforms.

Any ideas? I did a bit of digging but I'm not sure how well supported `DOMParser` and `parseFromString` are.
