### ISSUE TITLE
Polyfills not working in prod?

### ISSUE THREAD

**Issue by nickoneill** [5calls/5calls#403]
I've included these specific es6-set polyfill in our webpack config with the assumption that it would fix some of these Set errors on older browsers - it doesn't appear that that's the case? What am I doing wrong with polyfills?

https://sentry.io/5calls/5-calls/issues/565001719/

```
ReferenceError: Set is not defined
  at __webpack_require__ (../webpack/bootstrap 44ee761fba2badf7eb34:19:1)
  at __webpack_require__ (../webpack/bootstrap 44ee761fba2badf7eb34:19:1)
  at call (index.tsx:3:1)
  at __webpack_require__ (../webpack/bootstrap 44ee761fba2badf7eb34:19:1)
  at call (../static/js/main.6e447c20.js:63756:18)
...
(5 additional frame(s) were not displayed)
```

**Comment by nickoneill** [comment]
I think I was using es6-set wrong. Someone suggested core-js instead, and I started using it here: c44be63ea87a37919933d0785e2052c7fe0de3e8

Looks much better so far.

**Comment by nickoneill** [comment]
Looks good with our previous update 👍
